# Site settings
title: Löbtau Lachse
email: kontak@loebtau-lachse.de
description: "Löbtau Lachse: Die sportliche Frisbee-Gemeinschaft aus Löbtau, Dresden."
baseurl: ""
url: "https://yannickspoerl.de/loebtau-lachse"
github_username:  yannickspoerl

# Build settings
markdown: kramdown
