# Site settings
title: Löbtau Lachse
email: kontak@loebtau-lachse.de
description: "Löbtau Lachse: Die sportliche Frisbee-Gemeinschaft aus Löbtau, Dresden."
baseurl: ""
url: "https://loebtau-lachse.de"
twitter_username: yannickspoerl
github_username:  yannickspoerl

# Build settings
markdown: kramdown
